; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
extra_configs = secrets.ini

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
lib_deps = 
	adafruit/Adafruit NeoPixel@^1.15.5
	lovyan03/LovyanGFX@^1.2.21
	knolleary/PubSubClient@^2.8

debug_tool = esp-builtin
build_type = debug

build_flags =
  -DWIFI_SSID=${secrets.WIFI_SSID}
  -DWIFI_PASS=${secrets.WIFI_PASS}
  -DMQTT_HOST=${secrets.MQTT_HOST}
  -DMQTT_USER=${secrets.MQTT_USER}
  -DMQTT_PASS=${secrets.MQTT_PASS}
